// source: Core/ProtoDatabaseContainer.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.Mayfair.ProtocolDatabaseEnvelope');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.google.protobuf.Any');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Mayfair.ProtocolDatabaseEnvelope = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.Mayfair.ProtocolDatabaseEnvelope, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.Mayfair.ProtocolDatabaseEnvelope.displayName = 'proto.Mayfair.ProtocolDatabaseEnvelope';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Mayfair.ProtocolDatabaseEnvelope.prototype.toObject = function(opt_includeInstance) {
  return proto.Mayfair.ProtocolDatabaseEnvelope.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Mayfair.ProtocolDatabaseEnvelope} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Mayfair.ProtocolDatabaseEnvelope.toObject = function(includeInstance, msg) {
  var f, obj = {
    exportsource: jspb.Message.getFieldWithDefault(msg, 1, ""),
    innermessage: (f = msg.getInnermessage()) && proto.google.protobuf.Any.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Mayfair.ProtocolDatabaseEnvelope}
 */
proto.Mayfair.ProtocolDatabaseEnvelope.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Mayfair.ProtocolDatabaseEnvelope;
  return proto.Mayfair.ProtocolDatabaseEnvelope.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Mayfair.ProtocolDatabaseEnvelope} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Mayfair.ProtocolDatabaseEnvelope}
 */
proto.Mayfair.ProtocolDatabaseEnvelope.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setExportsource(value);
      break;
    case 2:
      var value = new proto.google.protobuf.Any;
      reader.readMessage(value,proto.google.protobuf.Any.deserializeBinaryFromReader);
      msg.setInnermessage(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Mayfair.ProtocolDatabaseEnvelope.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.Mayfair.ProtocolDatabaseEnvelope.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Mayfair.ProtocolDatabaseEnvelope} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Mayfair.ProtocolDatabaseEnvelope.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getExportsource();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getInnermessage();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.google.protobuf.Any.serializeBinaryToWriter
    );
  }
};


/**
 * optional string exportSource = 1;
 * @return {string}
 */
proto.Mayfair.ProtocolDatabaseEnvelope.prototype.getExportsource = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.Mayfair.ProtocolDatabaseEnvelope.prototype.setExportsource = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional google.protobuf.Any innerMessage = 2;
 * @return {?proto.google.protobuf.Any}
 */
proto.Mayfair.ProtocolDatabaseEnvelope.prototype.getInnermessage = function() {
  return /** @type{?proto.google.protobuf.Any} */ (
    jspb.Message.getWrapperField(this, proto.google.protobuf.Any, 2));
};


/** @param {?proto.google.protobuf.Any|undefined} value */
proto.Mayfair.ProtocolDatabaseEnvelope.prototype.setInnermessage = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.Mayfair.ProtocolDatabaseEnvelope.prototype.clearInnermessage = function() {
  this.setInnermessage(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Mayfair.ProtocolDatabaseEnvelope.prototype.hasInnermessage = function() {
  return jspb.Message.getField(this, 2) != null;
};


