// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Core/ProtoDatabaseContainer.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Mayfair.Core.Code.Protocol {

  /// <summary>Holder for reflection information generated from Core/ProtoDatabaseContainer.proto</summary>
  public static partial class ProtoDatabaseContainerReflection {

    #region Descriptor
    /// <summary>File descriptor for Core/ProtoDatabaseContainer.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ProtoDatabaseContainerReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiFDb3JlL1Byb3RvRGF0YWJhc2VDb250YWluZXIucHJvdG8SB01heWZhaXIa",
            "GWdvb2dsZS9wcm90b2J1Zi9hbnkucHJvdG8iXAoYUHJvdG9jb2xEYXRhYmFz",
            "ZUVudmVsb3BlEhQKDGV4cG9ydFNvdXJjZRgBIAEoCRIqCgxpbm5lck1lc3Nh",
            "Z2UYAiABKAsyFC5nb29nbGUucHJvdG9idWYuQW55Qh2qAhpNYXlmYWlyLkNv",
            "cmUuQ29kZS5Qcm90b2NvbGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.AnyReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Mayfair.Core.Code.Protocol.ProtocolDatabaseEnvelope), global::Mayfair.Core.Code.Protocol.ProtocolDatabaseEnvelope.Parser, new[]{ "ExportSource", "InnerMessage" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  ///This should never be modified.
  ///This is used by the database exporter to store data in a unity format.
  /// </summary>
  public sealed partial class ProtocolDatabaseEnvelope : pb::IMessage<ProtocolDatabaseEnvelope> {
    private static readonly pb::MessageParser<ProtocolDatabaseEnvelope> _parser = new pb::MessageParser<ProtocolDatabaseEnvelope>(() => new ProtocolDatabaseEnvelope());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ProtocolDatabaseEnvelope> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Mayfair.Core.Code.Protocol.ProtoDatabaseContainerReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ProtocolDatabaseEnvelope() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ProtocolDatabaseEnvelope(ProtocolDatabaseEnvelope other) : this() {
      exportSource_ = other.exportSource_;
      innerMessage_ = other.innerMessage_ != null ? other.innerMessage_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ProtocolDatabaseEnvelope Clone() {
      return new ProtocolDatabaseEnvelope(this);
    }

    /// <summary>Field number for the "exportSource" field.</summary>
    public const int ExportSourceFieldNumber = 1;
    private string exportSource_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ExportSource {
      get { return exportSource_; }
      set {
        exportSource_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "innerMessage" field.</summary>
    public const int InnerMessageFieldNumber = 2;
    private global::Google.Protobuf.WellKnownTypes.Any innerMessage_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Protobuf.WellKnownTypes.Any InnerMessage {
      get { return innerMessage_; }
      set {
        innerMessage_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ProtocolDatabaseEnvelope);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ProtocolDatabaseEnvelope other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ExportSource != other.ExportSource) return false;
      if (!object.Equals(InnerMessage, other.InnerMessage)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (ExportSource.Length != 0) hash ^= ExportSource.GetHashCode();
      if (innerMessage_ != null) hash ^= InnerMessage.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (ExportSource.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ExportSource);
      }
      if (innerMessage_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(InnerMessage);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (ExportSource.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ExportSource);
      }
      if (innerMessage_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(InnerMessage);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ProtocolDatabaseEnvelope other) {
      if (other == null) {
        return;
      }
      if (other.ExportSource.Length != 0) {
        ExportSource = other.ExportSource;
      }
      if (other.innerMessage_ != null) {
        if (innerMessage_ == null) {
          InnerMessage = new global::Google.Protobuf.WellKnownTypes.Any();
        }
        InnerMessage.MergeFrom(other.InnerMessage);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            ExportSource = input.ReadString();
            break;
          }
          case 18: {
            if (innerMessage_ == null) {
              InnerMessage = new global::Google.Protobuf.WellKnownTypes.Any();
            }
            input.ReadMessage(InnerMessage);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
